spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scrd
    username: root
    password: wntkfkd11!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
    defer-datasource-initialization: true

#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#
#kakao:
#  client:
#    id: 98d219c4217898cf3c7e2d139e23b5ca
#    secret: 1i2DgRs2GIAQI43CJEBoSem9gVJqXsHT
#  redirect:
#    uri: http://localhost:8080/api/login
#
## JWT 설정은 kakao와 별도로 정의해야 함
#jwt:
#  secret: "gjITbPwjXp3ZvUfcGx+sxaeB3Mdxcbfur9ZGZkmwgQs="
#  expiration: 3600000  # JWT 토큰 만료 시간 (1시간)


