spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.cr6kassm00po.ap-northeast-2.rds.amazonaws.com:3306/scrd
    username: admin
    password: wntkfkd11!
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: false
    defer-datasource-initialization: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

logging:
  level:
    org:
      springframework:


custom:
  host:
    client: http://localhost:3000,https://elegant-puppy-7c8193.netlify.app/
  jwt:
    secret: "gjITbPwjXp3ZvUfcGx+sxaeB3Mdxcbfur9ZGZkmwgQs="
    expire-time-ms:  10000 # 만료 시간 설정 (1시간) = 3600000
    refresh-expire-time-ms: 20000

kakao:
  api:
    key:
      client: "6b4d8cc48ec73499504d519e26c84c91"  # 클라이언트 키
    #    auth-url: "https://kauth.kakao.com/oauth/authorize"
#    redirect-uri: "http://localhost:8080/scrd/auth/kakao-login"


